name: 個人開発プロジェクト
about: 個人開発プロジェクトを計画する
labels: [project]
body:
  - type: input
    id: project-name
    attributes:
      label: プロジェクト名
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: 目的
    validations:
      required: true
  - type: textarea
    id: skills
    attributes:
      label: 対応スキル・資格
  - type: textarea
    id: tech
    attributes:
      label: 使用技術
  - type: textarea
    id: mvp
    attributes:
      label: MVP
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: 完了条件
